<?php

return [
    'about_gallery' => [
        'images/refugio/espacios/bosque-magico.png' => 'Bosque mágico — Refugio Gastronómico',
        'images/refugio/espacios/parking.png' => 'Estacionamiento — Refugio Gastronómico',
        'images/refugio/espacios/play-bar.png' => 'Play bar — Refugio Gastronómico',
        'images/refugio/espacios/zon-central.png' => 'Zona central — Refugio Gastronómico',
    ],

    'logos' => [
        'ahumare' => 'images/refugio/logos-finales/AHUMARE.png',
        'anticuchos-anticuching' => 'images/refugio/logos-finales/ANTICUCHING.png',
        'barrio-mancora' => 'images/refugio/logos-finales/BARRIO MANCORA.png',
        'barrio-wok' => 'images/refugio/logos-finales/BARRIO WOK.png',
        'broaster-bros' => 'images/refugio/logos-finales/BROS.png',
        'caldos-doris' => 'images/refugio/logos-finales/CALDOS DORIS.png',
        'cavenecia' => 'images/refugio/logos-finales/CAVENECIA.png',
        'cremoladas-curich' => 'images/refugio/logos-finales/CURICH.png',
        'don-melchor' => 'images/refugio/logos-finales/DON MELCHOR.png',
        'hanzo-express' => 'images/refugio/logos-finales/HANZO.png',
        'la-22-sangucheria' => 'images/refugio/logos-finales/LA 22.png',
        'la-victoria' => 'images/refugio/logos-finales/LA VICTORIA.png',
        'lili-blue' => 'images/refugio/logos-finales/LILI BLUE.png',
        'limanesas' => 'images/refugio/logos-finales/LIMANESA.png',
        'madre-amazonica' => 'images/refugio/logos-finales/MADRE AMAZONICA.png',
        'mr-smash' => 'images/refugio/logos-finales/MR SMASH.png',
        'nashmys' => 'images/refugio/logos-finales/NASHMY.png',
        'ramen-ya' => 'images/refugio/logos-finales/RAMEN YA.png',
        'refugio-bar' => 'images/refugio/logos-finales/REFUGIO BAR.png',
        'saltao-wok-food' => 'images/refugio/logos-finales/SALTAO.png',
        'sisa-coffee-wine' => 'images/refugio/logos-finales/SISA.png',
        'tortas-gaby' => 'images/refugio/logos-finales/TORTAS.png',
    ],

    'banners' => [
        'ahumare' => 'images/refugio/carteles/AHUMARE.png',
        'anticuchos-anticuching' => 'images/refugio/carteles/ANTICUCHING.png',
        'barrio-mancora' => 'images/refugio/carteles/BARRIO MANCORA.png',
        'barrio-wok' => 'images/refugio/carteles/BARRIO WORK.png',
        'broaster-bros' => 'images/refugio/carteles/BROS.png',
        'caldos-doris' => 'images/refugio/carteles/CALDOS DORIS.png',
        'cavenecia' => 'images/refugio/carteles/CAVENECIA.png',
        'cremoladas-curich' => 'images/refugio/carteles/CURICH.png',
        'don-melchor' => 'images/refugio/carteles/DON MELCHOR.png',
        'hanzo-express' => 'images/refugio/carteles/HANZO.png',
        'la-22-sangucheria' => 'images/refugio/carteles/LA22.png',
        'la-victoria' => 'images/refugio/carteles/LA VICTORIA.png',
        'lili-blue' => 'images/refugio/carteles/LILI BLUE.png',
        'limanesas' => 'images/refugio/carteles/LIMANESAS.png',
        'madre-amazonica' => 'images/refugio/carteles/MADRE AMAZONICA.png',
        'mr-smash' => 'images/refugio/carteles/MR SMASH.png',
        'nashmys' => 'images/refugio/carteles/NASHMY.png',
        'ramen-ya' => 'images/refugio/carteles/RAMEN YA.png',
        'refugio-bar' => 'images/refugio/carteles/BAR REFUGIO.png',
        'saltao-wok-food' => 'images/refugio/carteles/SALTAO.png',
        'sisa-coffee-wine' => 'images/refugio/carteles/SISA.png',
        'tortas-gaby' => 'images/refugio/carteles/TORTAS GABY.png',
    ],

    'frontis' => [
        'cavenecia' => 'images/refugio/frontis/1-cavenecia.png',
        'don-melchor' => 'images/refugio/frontis/2-don-melchor.png',
        'anticuchos-anticuching' => 'images/refugio/frontis/3-anticuching.png',
        'madre-amazonica' => 'images/refugio/frontis/4-madre-amazonica.png',
        'ahumare' => 'images/refugio/frontis/6-ahumare.png',
        'barrio-mancora' => 'images/refugio/frontis/7-barrio-mancora.png',
        'barrio-wok' => 'images/refugio/frontis/8-barrio-wok.png',
        'tortas-gaby' => 'images/refugio/frontis/9-tortas-gaby.png',
        'la-victoria' => 'images/refugio/frontis/10-la-victoria.png',
        'lili-blue' => 'images/refugio/frontis/11-lili-blue.png',
        'broaster-bros' => 'images/refugio/frontis/12-bros.png',
        'saltao-wok-food' => 'images/refugio/frontis/13-saltao.png',
        'ramen-ya' => 'images/refugio/frontis/14-ramen-ya.png',
        'hanzo-express' => 'images/refugio/frontis/15-hanzo.png',
        'mr-smash' => 'images/refugio/frontis/16-mr-smash.png',
        'caldos-doris' => 'images/refugio/frontis/17-cados-doris.png',
        'limanesas' => 'images/refugio/frontis/18-limanesas.png',
        'refugio-bar' => 'images/refugio/frontis/refugio-bar.jpg',
        'nashmys' => 'images/refugio/frontis/nashmys.jpg',
        'sisa-coffee-wine' => 'images/refugio/frontis/sisa.jpg',
    ],

    'hero_video' => 'videos/video-principal.mp4',

    'hero_poster' => 'images/refugio/fondohome.jpg',

    'event_offers' => [
        'shows-musicales' => 'images/refugio/eventos/SHOW EN VIVO.jpg',
        'show-para-ninos' => 'images/refugio/eventos/SHOW INFANTIL.jpg',
        'organiza-tu-evento-con-nosotros' => 'images/refugio/eventos/EVENTOS.jpg',
        'organiza-tu-fiesta-infantil' => 'images/refugio/eventos/FIESTAS INFANTILES.jpg',
    ],
];
