<?php

return [
    'park_maps' => [
        'ahumare' => 'images/nuevo/MAPAS/MAPA WEB AHUMARE.png',
        'anticuchos-anticuching' => 'images/nuevo/MAPAS/MAPA WEB ANTICUCHING.png',
        'barrio-mancora' => 'images/nuevo/MAPAS/MAPA WEB BARRIO MANCORA.png',
        'barrio-wok' => 'images/nuevo/MAPAS/MAPA WEB BARRIO WOK.png',
        'broaster-bros' => 'images/nuevo/MAPAS/MAPA WEB BROS.png',
        'caldos-doris' => 'images/nuevo/MAPAS/MAPA WEB CALDOS DORIS.png',
        'cavenecia' => 'images/nuevo/MAPAS/MAPA WEB CAVENECIA.png',
        'cremoladas-curich' => 'images/nuevo/MAPAS/MAPA WEB CURICH.png',
        'don-melchor' => 'images/nuevo/MAPAS/MAPA WEB DON MELCHOR.png',
        'hanzo-express' => 'images/nuevo/MAPAS/MAPA WEB HANZO.png',
        'la-22-sangucheria' => 'images/nuevo/MAPAS/MAPA WEB LA 22.png',
        'la-victoria' => 'images/nuevo/MAPAS/MAPA WEB LA VICTORIA.png',
        'lili-blue' => 'images/nuevo/MAPAS/MAPA WEB LILI BLUE.png',
        'limanesas' => 'images/nuevo/MAPAS/MAPA WEB LIMANESAS.png',
        'madre-amazonica' => 'images/nuevo/MAPAS/MAPA WEB MADRE AMAZONICA.png',
        'mr-smash' => 'images/nuevo/MAPAS/MAPA WEB MR SMASH.png',
        'nashmys' => 'images/nuevo/MAPAS/MAPA WEB NASHMYS.png',
        'ramen-ya' => 'images/nuevo/MAPAS/MAPA WEB RAMEN YA.png',
        'refugio-bar' => 'images/nuevo/MAPAS/MAPA WEB BAR REGUGIO.png',
        'saltao-wok-food' => 'images/nuevo/MAPAS/MAPA WEB SALTAO.png',
        'sisa-coffee-wine' => 'images/nuevo/MAPAS/MAPA WEB SISA.png',
        'tortas-gaby' => 'images/nuevo/MAPAS/MAPA WEB TORTAS GABY.png',
    ],

    'logos' => [
        'ahumare' => 'images/refugio/logos-finales/AHUMARE.png',
        'anticuchos-anticuching' => 'images/refugio/logos-finales/ANTICUCHING.png',
        'barrio-mancora' => 'images/refugio/logos-finales/BARRIO MANCORA.png',
        'barrio-wok' => 'images/refugio/logos-finales/BARRIO WOK.png',
        'broaster-bros' => 'images/refugio/logos-finales/BROS.png',
        'caldos-doris' => 'images/refugio/logos-finales/CALDOS DORIS.png',
        'cavenecia' => 'images/refugio/logos-finales/CAVENECIA.png',
        'cremoladas-curich' => 'images/refugio/logos-finales/CURICH.png',
        'don-melchor' => 'images/refugio/logos-finales/DON MELCHOR.png',
        'hanzo-express' => 'images/refugio/logos-finales/HANZO.png',
        'la-22-sangucheria' => 'images/refugio/logos-finales/LA 22.png',
        'la-victoria' => 'images/refugio/logos-finales/LA VICTORIA.png',
        'lili-blue' => 'images/refugio/logos-finales/LILI BLUE.png',
        'limanesas' => 'images/refugio/logos-finales/LIMANESA.png',
        'madre-amazonica' => 'images/refugio/logos-finales/MADRE AMAZONICA.png',
        'mr-smash' => 'images/refugio/logos-finales/MR SMASH.png',
        'nashmys' => 'images/refugio/logos-finales/NASHMY.png',
        'ramen-ya' => 'images/refugio/logos-finales/RAMEN YA.png',
        'refugio-bar' => 'images/refugio/logos-finales/REFUGIO BAR.png',
        'saltao-wok-food' => 'images/refugio/logos-finales/SALTAO.png',
        'sisa-coffee-wine' => 'images/refugio/logos-finales/SISA.png',
        'tortas-gaby' => 'images/refugio/logos-finales/TORTAS.png',
    ],

    'dishes' => [
        'ahumare' => 'images/nuevo/platos/plato-1-ahumare.jpg',
        'anticuchos-anticuching' => 'images/nuevo/platos/plato-1-anticuching.jpg',
        'barrio-mancora' => 'images/nuevo/platos/plato-1-anticuching-barrio-mancora.jpg',
        'barrio-wok' => 'images/nuevo/platos/plato-1-barrio-wok.jpg',
        'broaster-bros' => 'images/nuevo/platos/plato-1-bros.jpg',
        'caldos-doris' => 'images/nuevo/platos/plato-1-doris.jpg',
        'cavenecia' => 'images/nuevo/platos/plato-1-cavenecia.jpg',
        'cremoladas-curich' => 'images/nuevo/platos/plato-1-curich.jpg',
        'don-melchor' => 'images/nuevo/platos/plato-1-melchor.jpg',
        'hanzo-express' => 'images/nuevo/platos/plato-1-hanzo.jpg',
        'la-22-sangucheria' => 'images/nuevo/platos/plato-1-la22.jpg',
        'la-victoria' => 'images/nuevo/platos/plato-1-lavictoria.jpg',
        'lili-blue' => 'images/nuevo/platos/plato-1-lili-blue.jpg',
        'limanesas' => 'images/nuevo/platos/plato-1-limanesas.jpg',
        'madre-amazonica' => 'images/nuevo/platos/plato-1-madre-amaronica.jpg',
        'mr-smash' => 'images/nuevo/platos/plato-1-mr-smash.jpg',
        'nashmys' => 'images/nuevo/platos/plato-1-nashmys.jpg',
        'ramen-ya' => 'images/nuevo/platos/plato-1-ramenya.jpg',
        'saltao-wok-food' => 'images/nuevo/platos/plato-1-saltao.jpg',
        'sisa-coffee-wine' => 'images/nuevo/platos/plato-1-sisa.jpg',
        'tortas-gaby' => 'images/nuevo/platos/plato-1-tortas-gaby.jpg',
    ],

    'banners' => [
        'ahumare' => 'images/refugio/carteles/AHUMARE.png',
        'anticuchos-anticuching' => 'images/refugio/carteles/ANTICUCHING.png',
        'barrio-mancora' => 'images/refugio/carteles/BARRIO MANCORA.png',
        'barrio-wok' => 'images/refugio/carteles/BARRIO WORK.png',
        'broaster-bros' => 'images/refugio/carteles/BROS.png',
        'caldos-doris' => 'images/refugio/carteles/CALDOS DORIS.png',
        'cavenecia' => 'images/refugio/carteles/CAVENECIA.png',
        'cremoladas-curich' => 'images/refugio/carteles/CURICH.png',
        'don-melchor' => 'images/refugio/carteles/DON MELCHOR.png',
        'hanzo-express' => 'images/refugio/carteles/HANZO.png',
        'la-22-sangucheria' => 'images/refugio/carteles/LA22.png',
        'la-victoria' => 'images/refugio/carteles/LA VICTORIA.png',
        'lili-blue' => 'images/refugio/carteles/LILI BLUE.png',
        'limanesas' => 'images/refugio/carteles/LIMANESAS.png',
        'madre-amazonica' => 'images/refugio/carteles/MADRE AMAZONICA.png',
        'mr-smash' => 'images/refugio/carteles/MR SMASH.png',
        'nashmys' => 'images/refugio/carteles/NASHMY.png',
        'ramen-ya' => 'images/refugio/carteles/RAMEN YA.png',
        'refugio-bar' => 'images/refugio/carteles/BAR REFUGIO.png',
        'saltao-wok-food' => 'images/refugio/carteles/SALTAO.png',
        'sisa-coffee-wine' => 'images/refugio/carteles/SISA.png',
        'tortas-gaby' => 'images/refugio/carteles/TORTAS GABY.png',
    ],

    'frontis' => [
        'cavenecia' => 'images/refugio/frontis/1-cavenecia.png',
        'don-melchor' => 'images/refugio/frontis/2-don-melchor.png',
        'anticuchos-anticuching' => 'images/refugio/frontis/3-anticuching.png',
        'madre-amazonica' => 'images/refugio/frontis/4-madre-amazonica.png',
        'ahumare' => 'images/refugio/frontis/6-ahumare.png',
        'barrio-mancora' => 'images/refugio/frontis/7-barrio-mancora.png',
        'barrio-wok' => 'images/refugio/frontis/8-barrio-wok.png',
        'tortas-gaby' => 'images/refugio/frontis/9-tortas-gaby.png',
        'la-victoria' => 'images/refugio/frontis/10-la-victoria.png',
        'lili-blue' => 'images/refugio/frontis/11-lili-blue.png',
        'broaster-bros' => 'images/refugio/frontis/12-bros.png',
        'saltao-wok-food' => 'images/refugio/frontis/13-saltao.png',
        'ramen-ya' => 'images/refugio/frontis/14-ramen-ya.png',
        'hanzo-express' => 'images/refugio/frontis/15-hanzo.png',
        'mr-smash' => 'images/refugio/frontis/16-mr-smash.png',
        'caldos-doris' => 'images/refugio/frontis/17-cados-doris.png',
        'limanesas' => 'images/refugio/frontis/18-limanesas.png',
    ],

    'page_banners' => [
        'restaurants' => 'images/nuevo/banners/que-te-provoca-hoy.jpg',
        'services' => 'images/nuevo/banners/nuestros-servicios.jpg',
        'events' => 'images/nuevo/banners/somos-elrefugio-de-tu-diversion.jpg',
    ],

    'exclusive_discounts' => [
        'ahumare' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/AHUMARE - APROBADO.png',
        'anticuchos-anticuching' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/ANTICUCHING - APROBADO.png',
        'barrio-mancora' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/BARRIO MANCORA - APROBADO.png',
        'barrio-wok' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/BARRIO WOK - APROBADO.png',
        'caldos-doris' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/CALDOS DORIS - APROBADO.png',
        'cavenecia' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/CAVENECIA - APROBADO.png',
        'hanzo-express' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/HANZO - APROBADO.png',
        'la-22-sangucheria' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/LA 22 - APROBADO.png',
        'limanesas' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/LIMANESAS - APROBADO.png',
        'mr-smash' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/SMASH - APROBADO.png',
        'nashmys' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/NASHMYS - APROBADO.png',
        'ramen-ya' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/RAMEN YA - APROBADO.png',
        'sisa-coffee-wine' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/SISA - APROBADO.png',
    ],
];
