<?php

return [
    'park_maps' => [
        'ahumare' => 'images/nuevo/MAPAS/MAPA WEB AHUMARE.png',
        'anticuchos-anticuching' => 'images/nuevo/MAPAS/MAPA WEB ANTICUCHING.png',
        'barrio-mancora' => 'images/nuevo/MAPAS/MAPA WEB BARRIO MANCORA.png',
        'barrio-wok' => 'images/nuevo/MAPAS/MAPA WEB BARRIO WOK.png',
        'broaster-bros' => 'images/nuevo/MAPAS/MAPA WEB BNROS.png',
        'caldos-doris' => 'images/nuevo/MAPAS/MAPA WEB CALDOS DORIS.png',
        'cavenecia' => 'images/nuevo/MAPAS/MAPA WEB CAVENECIA.png',
        'cremoladas-curich' => 'images/nuevo/MAPAS/MAPA WEB CURICH.png',
        'don-melchor' => 'images/nuevo/MAPAS/MAPA WEB DON MELCHOR.png',
        'hanzo-express' => 'images/nuevo/MAPAS/MAPA WEB HANZO.png',
        'la-22-sangucheria' => 'images/nuevo/MAPAS/MAPA WEB LA 22.png',
        'la-victoria' => 'images/nuevo/MAPAS/MAPA WEB LA VICTORIA.png',
        'lili-blue' => 'images/nuevo/MAPAS/MAPA WEB LILI BLUE.png',
        'limanesas' => 'images/nuevo/MAPAS/MAPA WEB LIMANESAS.png',
        'madre-amazonica' => 'images/nuevo/MAPAS/MAPA WEB MADRE AMAZONICA.png',
        'mr-smash' => 'images/nuevo/MAPAS/MAPA WEB MR SMASH.png',
        'nashmys' => 'images/nuevo/MAPAS/MAPA WEB NASHMYS.png',
        'ramen-ya' => 'images/nuevo/MAPAS/MAPA WEB RAMEN YA.png',
        'refugio-bar' => 'images/nuevo/MAPAS/MAPA WEB BAR REGUGIO.png',
        'saltao-wok-food' => 'images/nuevo/MAPAS/MAPA WEB SALTAO.png',
        'sisa-coffee-wine' => 'images/nuevo/MAPAS/MAPA WEB SISA.png',
        'tortas-gaby' => 'images/nuevo/MAPAS/MAPA WEB TORTAS GABY.png',
    ],

    'logos' => [
        'ahumare' => 'images/nuevo/LOGOS/ahumare.png',
        'anticuchos-anticuching' => 'images/nuevo/LOGOS/Logo Anticuching.png',
        'barrio-mancora' => 'images/nuevo/LOGOS/barrio-mancora.png',
        'barrio-wok' => 'images/nuevo/LOGOS/BARRIO WOK.png',
        'broaster-bros' => 'images/nuevo/LOGOS/LOGOTIPO BROS impresión.png',
        'caldos-doris' => 'images/nuevo/LOGOS/LOGO CALDOS DORIS.png',
        'cavenecia' => 'images/nuevo/LOGOS/logo-cavenecia.png',
        'cremoladas-curich' => 'images/nuevo/LOGOS/LOGOCURICH-INDECOPI.png',
        'don-melchor' => 'images/nuevo/LOGOS/melchor.png',
        'hanzo-express' => 'images/nuevo/LOGOS/LOGO HANZO EXPRESS - FINAL.png',
        'la-22-sangucheria' => 'images/nuevo/LOGOS/LOGO 22.png',
        'la-victoria' => 'images/nuevo/LOGOS/la victoria.png',
        'lili-blue' => 'images/nuevo/LOGOS/LOGO LILI BLUE.png',
        'limanesas' => 'images/nuevo/LOGOS/Logo_Limanesa.png',
        'madre-amazonica' => 'images/nuevo/LOGOS/madre amazonica logo en pngggggg.png',
        'mr-smash' => 'images/nuevo/LOGOS/LOGOVECTORES.png',
        'nashmys' => "images/nuevo/LOGOS/Nashmy\u{00B4}s logo negro.png",
        'ramen-ya' => 'images/nuevo/LOGOS/logo ramen ya FINAL.png',
        'refugio-bar' => 'images/nuevo/LOGOS/REFUGIO BAR.png',
        'saltao-wok-food' => 'images/nuevo/LOGOS/Logo-Saltao.png',
        'sisa-coffee-wine' => 'images/nuevo/LOGOS/Logo_cafe_final-02.png',
        'tortas-gaby' => 'images/nuevo/LOGOS/TORTAS GABY_logotipo final-01.png',
    ],

    'dishes' => [
        'ahumare' => 'images/nuevo/platos/plato-1-ahumare.jpg',
        'anticuchos-anticuching' => 'images/nuevo/platos/plato-1-anticuching.jpg',
        'barrio-mancora' => 'images/nuevo/platos/plato-1-anticuching-barrio-mancora.jpg',
        'barrio-wok' => 'images/nuevo/platos/plato-1-barrio-wok.jpg',
        'broaster-bros' => 'images/nuevo/platos/plato-1-bros.jpg',
        'caldos-doris' => 'images/nuevo/platos/plato-1-doris.jpg',
        'cavenecia' => 'images/nuevo/platos/plato-1-cavenecia.jpg',
        'cremoladas-curich' => 'images/nuevo/platos/plato-1-curich.jpg',
        'don-melchor' => 'images/nuevo/platos/plato-1-melchor.jpg',
        'hanzo-express' => 'images/nuevo/platos/plato-1-hanzo.jpg',
        'la-22-sangucheria' => 'images/nuevo/platos/plato-1-la22.jpg',
        'la-victoria' => 'images/nuevo/platos/plato-1-lavictoria.jpg',
        'lili-blue' => 'images/nuevo/platos/plato-1-lili-blue.jpg',
        'limanesas' => 'images/nuevo/platos/plato-1-limanesas.jpg',
        'madre-amazonica' => 'images/nuevo/platos/plato-1-madre-amaronica.jpg',
        'mr-smash' => 'images/nuevo/platos/plato-1-mr-smash.jpg',
        'nashmys' => 'images/nuevo/platos/plato-1-nashmys.jpg',
        'ramen-ya' => 'images/nuevo/platos/plato-1-ramenya.jpg',
        'saltao-wok-food' => 'images/nuevo/platos/plato-1-saltao.jpg',
        'sisa-coffee-wine' => 'images/nuevo/platos/plato-1-sisa.jpg',
        'tortas-gaby' => 'images/nuevo/platos/plato-1-tortas-gaby.jpg',
    ],

    'page_banners' => [
        'restaurants' => 'images/nuevo/banners/que-te-provoca-hoy.jpg',
        'services' => 'images/nuevo/banners/nuestros-servicios.jpg',
        'events' => 'images/nuevo/banners/somos-elrefugio-de-tu-diversion.jpg',
    ],

    'exclusive_discounts' => [
        'ahumare' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/AHUMARE - APROBADO.png',
        'anticuchos-anticuching' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/ANTICUCHING - APROBADO.png',
        'barrio-mancora' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/BARRIO MANCORA - APROBADO.png',
        'barrio-wok' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/BARRIO WOK - APROBADO.png',
        'caldos-doris' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/CALDOS DORIS - APROBADO.png',
        'cavenecia' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/CAVENECIA - APROBADO.png',
        'hanzo-express' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/HANZO - APROBADO.png',
        'la-22-sangucheria' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/LA 22 - APROBADO.png',
        'limanesas' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/LIMANESAS - APROBADO.png',
        'mr-smash' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/SMASH - APROBADO.png',
        'nashmys' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/NASHMYS - APROBADO.png',
        'ramen-ya' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/RAMEN YA - APROBADO.png',
        'sisa-coffee-wine' => 'images/nuevo/DESCUENTOS EXCLUSIVOS/SISA - APROBADO.png',
    ],
];
